language: bash
services:
- docker
branches:
  only:
  - main
addons:
  ssh_known_hosts: $server_ip
before_install:
- echo "Produce SSH Key"
- openssl aes-256-cbc -K $encrypted_3facdd645a02_key -iv $encrypted_3facdd645a02_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- echo "Auth SSH Key"
- chmod 600 ~/.ssh/id_rsa
before_script:
  - echo "Login Ali ACR"
  - docker login --username=$ALI_USERNAME -p=$ALI_PASSWORD registry.cn-shanghai.aliyuncs.com
script:
  - echo "Build Docker"
  - docker build -t latest .
  - echo "Tag Docker"
  - docker tag latest registry.cn-shanghai.aliyuncs.com/aegean-next/pioneer-member:latest
  - echo "Push Docker"
  - docker push registry.cn-shanghai.aliyuncs.com/aegean-next/pioneer-member:latest
affter_success:
  - echo "Login Ali Service"
  - ssh -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa root@$server_ip "  - docker login --usern; me=$ALI_USERNAME -p=$ALI_PASSWORD registry.cn-shanghai.aliyuncs.com；cd /root/.docker-config; docker-compose up -d; exit"